### ISSUE TITLE
zephyr: Serial Recovery uploads to the slot 0 (instead of slot 1)

### ISSUE THREAD

**Issue by amateusz** [mcu-tools/mcuboot#1085] opened 2021-08-02 11:33 UTC
# :star: UPDATE :star::

Serial recovery seems to have slot 0 indeed hardcoded in `boot_serial/src/boot_serial.c:277`:
`rc = flash_area_open(flash_area_id_from_multi_image_slot(img_num, 0), &fap);`
As I understand from `usb_dfu.c` the upgrade slot should depend on Konfigs (`CONFIG_SINGLE_APPLICATION_SLOT`) and presence of the `image_1` partition. 
Please confirm that I got it right before I start to fix it.

---
## Serial recovery upload directly overwrites slot 0, skipping the whole test/swap/revert cycle.
  
  
I have a custom nrf52840 board with (USB & Serial) and I'm trying to make MCUboot to work through both transports.
 
### USB DFU firmware update flow works as intended :heavy_check_mark: :
- We start with working 1.0.0.3

```
Images:
 image=0 slot=0
    version: 1.0.0.3
    bootable: false
    flags: 
    hash: Unavailable
Split status: N/A (0)
```
- `dfu-util -D build/zephyr/zephyr.signed.bin -a "image-1"`

(The new image here is 1.0.0.4)

```
Images:
 image=0 slot=0
    version: 1.0.0.3
    bootable: false
    flags: 
    hash: Unavailable
 image=0 slot=1
    version: 1.0.0.4
    bootable: false
    flags: 
    hash: Unavailable
Split status: N/A (0)
```
- bootloader swaps and tests `Swap type: test`
- once confirmed, only the new image persists 
```
Images:
 image=0 slot=0
    version: 1.0.0.4
    bootable: false
    flags: 
    hash: Unavailable
```

## But Serial recovery always uploads to the slot 0:
(The new image here is 1.0.0.5)

```
Images:
 image=0 slot=0
    version: 1.0.0.3
    bootable: false
    flags: 
    hash: Unavailable
 image=0 slot=1
    version: 1.0.0.4
    bootable: false
    flags: 
    hash: Unavailable
Split status: N/A (0)
```
`$ ~/go/bin/mcumgr --timeout 500000 --conntype serial --connstring "dev=/dev/serial/by-id/usb-FTDI_FT232R_*****-port0,baud=115200" image upload -e zephyr/zephyr.signed.bin`

`$ ~/go/bin/mcumgr --timeout 500000 --conntype serial --connstring "dev=/dev/serial/by-id/usb-FTDI_FT232R_*****-port0,baud=115200" image list`

```
Images:
 image=0 slot=0
    version: 1.0.0.5
    bootable: false
    flags: 
    hash: Unavailable
 image=0 slot=1
    version: 1.0.0.4
    bootable: false
    flags: 
    hash: Unavailable
Split status: N/A (0)
```

I'm asking for your help as I couldn't narrow it down on my own

---

I'm building with zephyr 2.5.0
`*** Booting Zephyr OS build zephyr-v2.5.0-66-g351573f033ab  ***`

My MCUboot is @ 7a519682

**Comment by de-nordic** [comment] 2021-08-06 12:58
@amateusz The serial recovery is designed to always upload to primary slot, because it is recovery: it is used to fix your board when your primary application fails and the board, except for being able to run mcuboot, is paperweight. 
This behaviour can be altered with https://github.com/mcu-tools/mcuboot/commit/6c8932e9d044042cf882c62e83012081436d8cc9

In case of USB DFU I think that there is a bug; the USB DFU, when enabled for mcuboot, should always allow to upload to primary slot and alternatively to secondary; it makes no sense to upload to secondary slot, from the mcuboot, as  there is not app running, at this point from primary slot - this is similar to recovery scenario.

Uploading to secondary slot only makes sense when you have running application, because you can not overwrite the active application, which is in the primary slot.

**Comment by de-nordic** [comment] 2021-08-06 13:00
I have allowed myself to tag the title of your issue with "zephyr", as this is zephyr specific issue.

**Comment by d3zd3z** [comment] 2021-08-12 21:11
Is there a requirement to be able to serial recovery upload to slot 1? If so, this should be marked as an enhancement. Otherwise, I think this should be closed.

**Comment by nvlsianpu** [comment] 2021-08-16 14:23
Updating the primary slot with USB DFU class  (by default ) as mcuboot recovery method is intentional behavior.

**Comment by d3zd3z** [comment] 2021-08-16 20:20
I'll go ahead an close this issue, then. If there is a need to be able to write to slot 1 from serial recovery, it'd probably be best to open a new issue and explain there why that functionality is needed. We can then call it an enhancement, since the existing functionality is behaving as designed.

**Closed by d3zd3z** 2021-08-16 20:20 UTC
